### PR TITLE
Add generated types, tests for generated types, and script that generates Capnp types from ROS

### PR DESCRIPTION
**Pull request by TheDash**
This PR adds three notable chunks:

1. A script to generate Capnp schemas from ROS message, potentially modifiable later to accept other formats. Found here: https://github.com/TheDash/gams/blob/master/scripts/linux/generate_schemas.py. Wiki usage is here: https://github.com/jredmondson/gams/wiki/ROS-Porting-Tools

2. Brief amount of test code. The test code is found in tests/ and is added to travis.yaml. At the moment, 4 of the test cases fail (reading the values of an array after being retrieved from the KB) all related to the same issue. I'm not sure why. The documentation of Capnproto is lackluster to say the best about this. I've followed it to a T,  there may be a bug with how this flows through the KB internally. Perhaps more eyes on the issue will help.

The other tests loading schemas dynamically and setting/receiving other values of a Capnproto generated class and those pass.

3. Generated types live in src/gams/types/. There are roughly ~40? or so, to be added or removed at our leisure if we don't like them or don't see the point. They are just a starting point. There are many other ROS types out there that I expect people will see fit/custom types people will make PRs for into GAMS as time goes on.

A second set of eyes on some of the issues would be appreciated, feedback etc is welcome :call_me_hand: Iterating, test coverage is brief and not meant to be all encompassing for the types/fields, I believe a lot of it is handled in tests/test_any.cpp inside of the madara repo. This was just meant to at least demo the types being used and show they can all be loaded.

### CODE REVIEW

**Comment by TheDash** [comment]
Thank you! This will help me sleep tonight. What is the point of setRanges()?


Side point: I believe I read from somewhere that a .so of these types was necessary for the Java and Python ports. Curious on thoughts regarding that

**Comment by dskyle** [comment]
It's meant for copying values from a reader of a separate already built message.

The .so file is only for Cereal based types. For capnproto types, Java and Python can just use the schemes.

**Comment by TheDash** [comment]
Its worth it to note that the above point is *only* true for lists and blobs. Structs (such as Header) still require a final .setHeader() to be called back on them. Posting this statement for any future potential onlookers working with the Capnproto generated types.

**Comment by dskyle** [comment]
Are you sure? It seems to work for me without setHeader.

**Comment by TheDash** [comment]
I tried it without setHeader and I had the tests targeting the header fields fail (3) I'm just in a rebuild of gams right now, I can confirm in a moment.

**Comment by TheDash** [comment]
image

Running with setHeader()

**Comment by dskyle** [comment]
Oh, I see. You didn't fully apply my patch. You shouldn't have a second MallocMessageBuilder in test_imu. That approach functions, and does indeed require using setHeader, but it's wasteful and involves extra copying. The better approach is the one in my patch: just call initHeader() and use that builder.

**Comment by TheDash** [comment]
Thanks!

What about for the dynamic structs, how does one initializes those fields?

E.g i have

Dyn.set("header", header). Does it accept the return from initHeader? The dox break down here so I wasn't sure

**Comment by TheDash** [comment]
The clang build has failed. I notice also that we are using Ubuntu 14.04 on travis, but I am developing in 16.04, what is everyone else developing in?

Note error is: bin/test_types File not found.

**Comment by jredmondson** [comment]
David, I'll leave this to you to merge when you feel it's ready.

**Comment by dskyle** [comment]
Devon, are you stuck on that linker error? The crux of it is we rely on the Ubuntu boost packages currently, but those only fully support gcc. We've skated by because what we've used so far as been header only, or not used the incompatible parts of the standard library.

Also, we'd need to address what this does to the build system before merging. Not only are builds not parallelizable with this, but it seems every build rebuilds everything, because the schemas get built every time, and MPC seems to think every .cpp is dependent on them. Does libGAMS itself use the schemas? If not, the CAPN_Files shouldn't be directly associated with it, and could be a secondary project.

**Comment by TheDash** [comment]
@dskyle I haven't had a chance to look more into it past my initial investigations. I was going to look into it more on this Sunday. It may be that I just need to tell the build on travis to use a newer version of boost to be compatible with clang 5.0. I've searched around and seen that b2 can be compiled with clang with some flags. ./b2 toolset=clang cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++". Seems like a lot of work in travis just get this one clang build to work. Or perhaps I can isolate which symbols are causing the issue and find another way to solve the problem in my code to avoid it altogether.

libGAMS.so doesn't use the schemas directly. It's up to the user on that front. I had mentioned initially to build this as a separate .so (e.g libgams_datatypes.so) which is linked in, with a using_datatypes.mpb. I don't see too much of a problem of them being a shared lib. Namespacing can be the same. Once the datatypes are built, users shouldn't ever need to rebuild them unless the schemas are modified. 

We could trigger the build from the 'prereqs' flag in base_build.sh, as they technically are a prereq, and users wouldn't need to worry about building them again.

**Comment by TheDash** [comment]
Builds are passing -  however Java build ran into this:

[ERROR] Failed to execute goal on project gams: Could not resolve dependencies for project ai.gams:gams:jar:1.2.3: Could not find artifact ai.madara:madara:jar:3.2.4 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

The old clang build that was failing now passed https://travis-ci.org/jredmondson/gams/jobs/418742294

**Pull request merged**
