### PR TITLE
SW-7524 Use exceptions instead of special returns for GAMS ReferenceF…

### PR DESCRIPTION
**Pull request by sawtoothgeek**
…rame errors. Used in the public load metheds. Refactored to provide a load_exact method that does not throw if used internally. This way the gams test test_coordinates behaves as before.

### CODE REVIEW

**Comment by jredmondson** [comment]
@dskyle mind looking into this?

**Comment by dskyle** [comment]
@jredmondson do you know why Travis didn't run on this?

**Comment by dskyle** [comment]
@sawtoothgeek Please resolve the merge conflicts. Maybe that's why Travis didn't run.

**Comment by jredmondson** [comment]
@dskyle we're good to merge this one?

**Comment by sawtoothgeek** [comment]
Hi All, yes I think this ready to roll.

**Comment by dskyle** [comment]
Looks good, but since it's likely to break existing code, I'd like to wait until I'm in the office and readily available for questions before merging.

**Comment by sawtoothgeek** [comment]
Sounds good thanks David, should be easy to adjust the fix to meet reqs.

**Comment by sawtoothgeek** [comment]
Found a warning a I need to fix.

**Pull request merged**
