### PR TITLE
Fix creation of env.sh file inside base_build.sh

### PR DESCRIPTION
**Pull request by TheDash**
env.sh was receiving a file not found as it was not created initially. Added lines which check for existence

### CODE REVIEW

**Comment by TheDash** [comment]
For the env.sh file - I was getting a 'file not found' when it was trying to parse the env vars (e.g lines 717~+ onward). Did some more investigation.

When I checked the ls -l of it before putting this fix in, it was drwxr-xr-x and the owner was root. It must've occured when I did a "sudo !!" of the build, then cancelled the build, and then ran without sudo so that when it tried to access the file it didn't have permissions/said file not found.

User error on my part, however, I can go ahead and add a sudo check which will prevent users running this script with sudo if that's our intent so as to prevent any permission issues down the line.

**Comment by jredmondson** [comment]
Oh, sudo would definitely cause problems with a lot of stuff. Not sure we should be checking for that anywhere, as the places that would mess up permissions would be just about everywhere on a fresh install (e.g., many of the prereqs).

**Comment by TheDash** [comment]
To clarify, I'm talking about a sudo check as in preventing the user from running it with 'sudo ./base_build.sh', not to ensure that its run with sudo. I don't think its our intent for this to ever be run with sudo, except for explicit places in the code it's running 'sudo apt-get' , as we just saw how it caused errors in the build environment from a somehow sudo'd build.

**Comment by jredmondson** [comment]
OK. Did you want to cancel this one and submit the one that puts the sudo check up top?

**Comment by TheDash** [comment]
Yeah, I will do that.

**Comment by jredmondson** [comment]
If you wanted to touch the file ~ line 327 or so that might make sure the issue is fixed (and place it where the mkdir is originally done).

**Pull request closed without merging**
