### PR TITLE
Add generated types

### PR DESCRIPTION
**Pull request by TheDash**
Similar as prior PR but also

- fixes compiler warnings in test_types.cpp
- build is now parallelized
- now builds a libTYPES.so
- Added some .gitignore items relevant to generated files inside of src/gams/types, as well as other repos/modules that were being pulled in

### CODE REVIEW

**Comment by jredmondson** [comment]
Time is coming in just under the timeout. Does this look ok @dskyle ?

**Comment by dskyle** [comment]
@TheDash I pushed a small change to https://github.com/jredmondson/gams/tree/TheDash-master. Hopefully this will get our build times down a bit. Please merge into your fork, so it's part of this pull request.

**Comment by TheDash** [comment]
Build time on my end is about 58~ seconds with 12 cores prior to small fix @dskyle 
After small fix im getting 58~.

With 2 cores im getting 2m55s pre-fix. I ran this again and got 2m57s.
With 2 cores im getting 2m58 post-fix. I ran it again (2m59s) because I didn't believe it would be slower
In what situation is this meant to speed up? 

I noticed the .NOTPARALLEL is only for the generation - which is a simple parse and generate read/write and not actual compilation that is not being parallelized. My guess is that it happens so fast  that the generation doesn't have an effect on the build time in the scheme (no pun intended) of things.

Thoughts on this? I don't really think its reducing the times for *me* at all, correct me if I'm wrong/missing something. For others: this could be due to my processor being top notch so serial processing of such a small read/write phase has negligible effects. Compilation on other systems the differences may be noticeable.

**Comment by dskyle** [comment]
Thanks, I could be mistaken. Seemed faster to me, subjectively. Also, BTW, I figured out the "always regenerates" issue with capnproto: MPC handles the .c++ extension poorly, escaping in places it shouldn't. I'll have a fix pushed to Madara once CI is done, and then it would be useful to have it applied to GAMS as well. Fix is basically just to include a rename from .c++ to .cpp in the generation command.

**Comment by jredmondson** [comment]
Are we ready to go with a merge here? If not, what's left? People are waiting on this, e.g. Pawel

**Pull request merged**
